### ISSUE TITLE
newbie question: can you please document the pre-req pkgs?

### ISSUE THREAD

**Issue by flavio-fernandes** [shiftstack/dev-install#1]
Hello!

I've been interested in using ir standalone for a long time, but never managed to have it working.
I was trying it on 16, so maybe that was my problem. ;)

Can you elaborate a little bit more on what I need in order to invoke dev-install? Since the doc is
saying all I need to do is a "make" and the underlying makefile uses ansible, I suspect I
need makefile and ansible packages installed, ideally on a Centos 8.2 system, right? Anything else?

Thanks!

-- flaviof

**Comment by mdbooth** [comment]
Sorry, didn't see this! It should be just ansible... and make, I guess. Ansible should install anything else it requires automatically. If it didn't I'd consider that a bug.

Agree this sounds like something for the README.

**Comment by mdbooth** [comment]
Done.
