### ISSUE TITLE
Keep having to restart standalone_hostonly_snat.service

### ISSUE THREAD

**Issue by adduarte** [shiftstack/dev-install#28]
For some reason, in several deployments, even though the standalone_hostonly_snat.service status shows that it was run and it added the required iptables rule to the nat table  (iptables --list -t nat), the rule is not there. 
The solution is easy, just "sudo systemctl restart standalone_host_only_snat.service" reads the rule, 

Probably something else is clearing the iptables.

**Comment by EmilienM** [comment]
I couldn't reproduce it, i'm closing it but please re-open if you saw it recently.
